=== hakrsh/Distributed-IOT-ML-Platform/platform_manager/platform_manager/app_contract_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "version": {
      "type": "string"
    },
    "secret_key": {
      "type": "string"
    },
    "root_dir": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "cmd": {
      "type": "string"
    },
    "port": {
      "type": "integer"
    },
    "sensor_interface": {
      "type": "string"
    },
    "model_interface": {
      "type": "string"
    },
    "controller_interface": {
      "type": "string"
    },
    "sensors": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "function": {
              "type": "string"
            },
            "sensor_type": {
              "type": "string"
            }
          },
          "required": [
            "function",
            "sensor_type"
          ]
        }
      ]
    },
    "controllers": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "function": {
              "type": "string"
            },
            "args": {
              "type": "array",
              "items": [
                {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "type": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "name",
                    "type"
                  ]
                }
              ]
            },
            "controller_type": {
              "type": "string"
            }
          },
          "required": [
            "function",
            "args",
            "controller_type"
          ]
        }
      ]
    },
    "models": {
      "type": "array",
      "items": [
        {
          "type": "string"
        }
      ]
    },
    "health_check": {
      "type": "object",
      "properties": {
        "url": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "timeout": {
          "type": "integer"
        }
      },
      "required": [
        "url",
        "method",
        "timeout"
      ]
    },
    "requirements": {
      "type": "string"
    }
  },
  "required": [
    "version",
    "secret_key",
    "root_dir",
    "name",
    "cmd",
    "port",
    "sensor_interface",
    "model_interface",
    "controller_interface",
    "sensors",
    "controllers",
    "models",
    "health_check",
    "requirements"
  ]
}

=== hakrsh/Distributed-IOT-ML-Platform/sample_apps/patient_monitoring_app/app_contract.json
{
    "version": "1.0.0",
    "secret_key": "patient_monitoring_model_secret",
    "root_dir": "patient_monitoring_system",
    "name": "patient_monitoring_system",
    "cmd": "cd patient_monitoring_system/src && python3 app.py",
    "port": 8080,
    "sensor_interface" : "patient_monitoring_system/src/getdata.py",
    "model_interface": "patient_monitoring_system/src/models.json",
    "controller_interface": "patient_monitoring_system/src/sent_msg.py",
    "sensors":[
        {
            "function":"getspo2",
            "sensor_type":"Spo2"
        },
        {
            "function":"getpulserate",
            "sensor_type":"Pulse"
        },
        {
            "function":"gettemperature",
            "sensor_type":"Temperature"
        }
    ],
    "controllers":[
        {
            "function":"send_sms",
            "args":[
                {
                    "name":"phone",
                    "type":"string"
                },
                {
                    "name":"msg",
                    "type":"string"
                }
            ],
            "controller_type":"SMS"
        }
    ],
    "models":["vitals_check","diabetes_check"],
    "health_check":{
        "url":"http://localhost:8080/health",
        "method":"GET",
        "timeout":5
    },
    "requirements": "requirements.txt"
}

=== hakrsh/Distributed-IOT-ML-Platform/sample_apps/classroom_monitoring_app/app_contract.json
{
    "version": "1.0.0",
    "secret_key": "top_secret",
    "root_dir": "classroom_monitoring_system",
    "name": "classroom_monitoring_system",
    "cmd": "cd classroom_monitoring_system/src && python3 app.py",
    "port": 8080,
    "sensors":[
        {
            "function":"getcam1",
            "sensor_type":"cam"
        },
        {
            "function":"getcam2",
            "sensor_type":"cam"
        }
    ],
    "controllers":[
        {
            "function":"send_sms",
            "args":[
                {
                    "name":"phone",
                    "type":"string"
                },
                {
                    "name":"msg",
                    "type":"string"
                }
            ],
            "controller_type":"SMS"
        },
        {
            "function":"turn_on_light",
            "args":[
                {
                    "name":"signal",
                    "type":"int"
                }
            ],
            "controller_type":"light"
        }
    ],
    "models":["attendance_check","attentiveness_checker"],
    "health_check":{
        "url":"http://localhost:8080/health",
        "method":"GET",
        "timeout":5
    },
    "sensor_interface" : "classroom_monitoring_system/src/getdata.py",
    "model_interface": "classroom_monitoring_system/src/models.json",
    "controller_interface": "classroom_monitoring_system/src/controller.py",
    "requirements": "requirements.txt"
}
