=== hakrsh/Distributed-IOT-ML-Platform/platform_manager/platform_manager/app_contract_scheme.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "version": {
      "type": "string"
    },
    "secret_key": {
      "type": "string"
    },
    "root_dir": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "entry_point": {
      "type": "string"
    },
    "port": {
      "type": "integer"
    },
    "sensor_interface": {
      "type": "string"
    },
    "sensors": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "function": {
              "type": "string"
            },
            "sensor_type": {
              "type": "string"
            }
          },
          "required": [
            "function",
            "sensor_type"
          ]
        },
        {
          "type": "object",
          "properties": {
            "function": {
              "type": "string"
            },
            "sensor_type": {
              "type": "string"
            }
          },
          "required": [
            "function",
            "sensor_type"
          ]
        },
        {
          "type": "object",
          "properties": {
            "function": {
              "type": "string"
            },
            "sensor_type": {
              "type": "string"
            }
          },
          "required": [
            "function",
            "sensor_type"
          ]
        }
      ]
    },
    "health_check": {
      "type": "object",
      "properties": {
        "url": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "timeout": {
          "type": "integer"
        }
      },
      "required": [
        "url",
        "method",
        "timeout"
      ]
    },
    "requirements": {
      "type": "string"
    }
  },
  "required": [
    "version",
    "secret_key",
    "root_dir",
    "name",
    "entry_point",
    "port",
    "sensor_interface",
    "sensors",
    "health_check",
    "requirements"
  ]
}

=== hakrsh/Distributed-IOT-ML-Platform/sample_apps/patient_monitoring_system/app_contract.json
{
    "version": "1.0.0",
    "secret_key": "top_secret",
    "root_dir": "patient_monitoring_system",
    "name": "patient_monitoring_system",
    "entry_point": "patient_monitoring_system/src/app.py",
    "port": 8080,
    "sensor_interface" : "patient_monitoring_system/src/getdata.py",
    "sensors":[
        {
            "function":"getspo2",
            "sensor_type":"Spo2"
        },
        {
            "function":"getpulserate",
            "sensor_type":"Pulse"
        },
        {
            "function":"gettemperature",
            "sensor_type":"Temperature"
        }
    ],
    "health_check":{
        "url":"http://localhost:8080/health",
        "method":"GET",
        "timeout":5
    },
    "requirements": "requirements.txt"
}
