=== hakrsh/Distributed-IOT-ML-Platform/platform_manager/platform_manager/model_contract_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "version": {
      "type": "string"
    },
    "secret_key": {
      "type": "string"
    },
    "root_dir": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "tensorflow_support": {
      "type": "string"
    },
    "functions": {
      "type": "array",
      "items": [
        {
          "type": "object",
          "properties": {
            "module_path": {
              "type": "string"
            },
            "function_name": {
              "type": "string"
            },
            "function_input_type": {
              "type": "string"
            },
            "output_type": {
              "type": "string"
            },
            "api_endpoint": {
              "type": "string"
            },
            "methods": {
              "type": "array"
            }
          },
          "required": [
            "module_path",
            "function_name",
            "function_input_type",
            "output_type",
            "api_endpoint",
            "methods"
          ]
        }
      ]
    },
    "requirements": {
      "type": "string"
    },
    "readme": {
      "type": "string"
    }
  },
  "required": [
    "version",
    "secret_key",
    "root_dir",
    "name",
    "tensorflow_support",
    "functions",
    "requirements",
    "readme"
  ]
}

=== hakrsh/Distributed-IOT-ML-Platform/sample_apps/classroom_monitoring_model/model_contract.json
{
    "version": "1.0.0",
    "secret_key": "top_secret",
    "root_dir": "class_monitoring",
    "name": "Class Monitoring",
    "tensorflow_support": "yes",
    "functions": [
        {
            "module_path": "class_monitoring.attendance_checker.attendance_checker",
            "function_name": "count_students",
            "function_input_type": "ByteArray",
            "output_type": "integer",
            "api_endpoint": "attendance-checker",
            "methods": [
                {
                    "method_type": "POST",
                    "input_type": "json",
                    "input_schema": {
                        "type": "object",
                        "properties": [
                            {
                                "name": "image",
                                "type": "ByteArray"
                            }
                        ]
                    },
                    "response": {
                        "type": "string"
                    }
                }
            ]
        },
        {
            "module_path": "class_monitoring.attentiveness_checker.attentiveness_checker",
            "function_name": "get_attention",
            "function_input_type": "ByteArray",
            "output_type": "integer",
            "api_endpoint": "attentiveness-checker",
            "methods": [
                {
                    "method_type": "POST",
                    "input_type": "json",
                    "input_schema": {
                        "type": "object",
                        "properties": [
                            {
                                "name": "image",
                                "type": "ByteArray"
                            }
                        ]
                    },
                    "response": {
                        "type": "string"
                    }
                }
            ]
        }
    ],
    "requirements": "class_monitoring/requirements.txt",
    "readme": "class_monitoring/README.md"
}

=== hakrsh/Distributed-IOT-ML-Platform/sample_apps/patient_monitoring_model/model_contract.json
{
    "version": "1.0.0",
    "secret_key": "patient_monitoring_model_secret",
    "root_dir": "patient_monitoring",
    "name": "Patient Monitoring",
    "tensorflow_support":"yes",
    "functions": [
        {
            "module_path": "patient_monitoring.diabetes_checker.diabetes_checker",
            "function_name": "predict_diabetes",
            "function_input_type": "dict",
            "output_type": "string",
            "api_endpoint": "diabetes-checker",
            "methods": [
                {
                    "method_type": "POST",
                    "input_type": "json",
                    "input_schema": {
                        "type": "object",
                        "properties": [
                            {
                                "name": "glucose",
                                "type": "float"
                            },
                            {
                                "name": "insuline",
                                "type": "float"
                            },
                            {
                                "name": "age",
                                "type": "number"
                            },
                            {
                                "name": "bmi",
                                "type": "float"
                            }
                        ]
                    },
                    "response": {
                        "type": "string",
                        "enum": [
                            "true",
                            "false"
                        ]
                    }
                }
            ]
        },
        {
            "module_path": "patient_monitoring.vitals_checker.vitals_checker",
            "function_name": "predict_condition",
            "function_input_type": "dict",
            "output_type": "string",
            "api_endpoint": "vitals-checker",
            "methods": [
                {
                    "method_type": "POST",
                    "input_type": "json",
                    "input_schema": {
                        "type": "object",
                        "properties": [
                            {
                                "name": "spo2",
                                "type": "int"
                            },
                            {
                                "name": "pulse",
                                "type": "int"
                            },
                            {
                                "name": "temperature",
                                "type": "int"
                            }
                        ]
                    },
                    "response": {
                        "type": "string",
                        "enum": [
                            "true",
                            "false"
                        ]
                    }
                }
            ]
        }
    ],
    "requirements": "patient_monitoring/requirements.txt",
    "readme": "patient_monitoring/README.md"
}
